name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Ejecuta el workflow cuando se haga 'push' a la rama principal (main)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable" # Usa 'stable' o la versión que prefieras

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: |
          # ¡IMPORTANTE! Base-href debe ser el nombre de tu repositorio.
          # Esto es crucial para que los recursos (archivos CSS/JS) se carguen correctamente.
          flutter build web --release --base-href="/flutterMenu3d/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Directorio que contiene los archivos web generados
          publish_dir: ./build/web
          # Crea la rama 'gh-pages' para el despliegue
          publish_branch: gh-pages
